Name = input("Nama\t\t\t:")
Student_Number = input("NIM\t\t\t:")
Parallel_Class = input("Kelas Paralel\t\t:")
Place_Time_Of_Birth = input("Tempat/Tanggal Lahir\t:")
Adress = input("Alamat\t\t\t:")
Hobby = input("Hobby\t\t\t:")
Phone_Number = input("No.HP\t\t\t:")

print("\nNama\t\t\t:", Name)
print("NIM\t\t\t:", Student_Number)
print("Kelas Paralel\t\t:", Parallel_Class)
print("Tempat/Tanggal Lahir\t:", Place_Time_Of_Birth)
print("Alamat\t\t\t:", Adress)
print("Hobby\t\t\t:", Hobby)
print("No.HP\t\t\t:", Phone_Number)